[tox]
isolated_build = True
envlist = py39, linters, docs

[testenv]
deps =
    -r requirements_dev.txt

commands =
    pytest

[flake8]
extend-ignore = E203
per-file-ignores =
    src/flake8/formatting/_windows_color.py: N806
    tests/*: D
max-complexity = 10